name: deploy to production server to EC2

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.event.workflow_run.head_sha }}
        steps:
            - name: Check out repository code
              uses: actions/checkout@v5

            - name: ssh to prod server and create app folder
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_SSH_HOST }}
                  username: ${{ secrets.EC2_SSH_USER }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      echo "installing required packages and folder"
                      sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                      sudo usermod -aG docker $USER  
                      mkdir -p devops

            - name: Copy doker-compose file to prod server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.EC2_SSH_HOST }}
                  username: ${{ secrets.EC2_SSH_USER }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  source: docker-compose.yml
                  target: ~/devops

            - name: ssh to prod server and run the application
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_SSH_HOST }}
                  username: ${{ secrets.EC2_SSH_USER }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      echo "Running the application"
                      export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                      export DOCKER_TAG=${{ github.sha }}
                      echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ vars.DOCKERHUB_USER }} --password-stdin
                      cd ~/devops && docker compose down && docker compose up -d --force-recreate --pull always
